# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videogames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('genre', models.IntegerField(choices=[(0, 'Action'), (1, 'Adventure'), (2, 'Strategy'), (3, 'RPG'), (4, 'Sport')])),
                ('platform', models.IntegerField(choices=[(0, 'PC'), (1, 'PS4'), (2, 'XBOX ONE')])),
                ('score', models.IntegerField()),
                ('online', models.BooleanField()),
                ('pegi', models.IntegerField(choices=[(0, 'PEGI7'), (1, 'PEGI16'), (2, 'PEGI18')])),
            ],
        ),
    ]
